In [33]:
# noinspection PyUnresolvedReferences
from tensorflow.keras.datasets import mnist

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 6s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
test_images.shape

(10000, 28, 28)

In [5]:
len(train_images), len(test_images)

(60000, 10000)

In [6]:
len(train_labels), len(test_labels)

(60000, 10000)

In [7]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
from tensorflow import keras
# noinspection PyUnresolvedReferences
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax'),
])

In [10]:
model.compile(optimizer='rmsprop',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32')
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32')

In [11]:
model.fit(train_images, train_labels, epochs=5,batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 7ms/step - loss: 6.1604 - accuracy: 0.8974
Epoch 2/5
469/469 [==============================] - 3s 6ms/step - loss: 0.6675 - accuracy: 0.9513
Epoch 3/5
469/469 [==============================] - 3s 6ms/step - loss: 0.4254 - accuracy: 0.9644
Epoch 4/5
469/469 [==============================] - 3s 5ms/step - loss: 0.3508 - accuracy: 0.9708
Epoch 5/5
469/469 [==============================] - 3s 6ms/step - loss: 0.3207 - accuracy: 0.9757


In [12]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 97ms/step


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [13]:
predictions[0].argmax()

7

In [14]:
test_labels[0]

7

In [15]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.6112 - accuracy: 0.9652
Test accuracy: 0.9652000069618225


In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [17]:
#Représentation des données pour le réseau de neurones
import numpy as np
x = np.array(12)
x.ndim

0

In [18]:
x

array(12)

In [19]:
x = np.array([12,3,6,14,7])
x

array([12,  3,  6, 14,  7])

In [20]:
x.ndim

1

In [21]:
x = np.array([[12,3,6,14,7],
               [12,8,9,10,9],
              [3,4,9,0,89]
              ])
x

array([[12,  3,  6, 14,  7],
       [12,  8,  9, 10,  9],
       [ 3,  4,  9,  0, 89]])

In [22]:
x.ndim

2

In [23]:
x = np.array([[[5, 78, 2, 34, 0],
 [6, 79, 3, 35, 1],
 [7, 80, 4, 36, 2]],
 [[5, 78, 2, 34, 0],
 [6, 79, 3, 35, 1],
 [7, 80, 4, 36, 2]],
 [[5, 78, 2, 34, 0],
 [6, 79, 3, 35, 1],
 [7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [24]:
x.ndim

3

In [25]:
x.shape

(3, 3, 5)

In [26]:
x.dtype

dtype('int64')

In [27]:
train_images.dtype

dtype('float32')

In [28]:
train_images.ndim

2

In [29]:
# noinspection PyUnresolvedReferences
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [30]:
train_images.shape

(60000, 28, 28)

In [31]:
train_images.ndim

3

In [32]:
train_images.dtype

dtype('uint8')